/**
 * @file install.js
 * @description AI 桥接本机宿主安装器（注册 Native Messaging 宿主清单 + 平台入口）
 *
 * 用法：
 *   deno task ai-host-install --ext-id=<扩展ID>
 *   可选 --browser=chrome|edge（默认 chrome）
 *
 * 扩展 ID 从选项页「AI 桥接」Tab 复制（32 位 a-p 字母）。
 * 幂等：重复执行直接覆盖旧注册。
 *
 * ⚠️ Windows 实现要点：启动器由本脚本生成到用户状态目录，并把 deno 绝对路径烘焙进去。
 * Chrome 是长驻进程，其子进程环境可能滞后于当前 shell 的 PATH（装完 deno 后未重启
 * Chrome 时尤为典型），依赖 `deno` 命令解析会导致宿主秒退（"Native host has exited"）。
 * 启动器必须保持纯 ASCII：cmd.exe 以 ANSI 代码页解析批处理，UTF-8 中文注释会破坏解析。
 * @encoding UTF-8
 */

import { join } from 'jsr:@std/path@^1.0.8';

const HOST_NAME = 'com.betterbrowse.bridge';
const HOST_DESCRIPTION = 'BetterBrowse AI 桥接本机宿主（由 Chrome 按需拉起，非常驻服务）';

/** 解析命令行参数（--key=value 形式） */
function parseArgs(args) {
  const parsed = {};
  for (const arg of args) {
    const match = /^--([a-zA-Z-]+)=(.*)$/.exec(arg);
    if (match) parsed[match[1]] = match[2];
  }
  return parsed;
}

/**
 * 校验扩展 ID（Chrome 无序 ID：32 位 a-p 小写字母）
 * @param {string} id
 */
function isValidExtensionId(id) {
  return /^[a-p]{32}$/.test(String(id || '').trim());
}

/**
 * 用户状态目录（bridge.json 自发现文件与生成的启动器所在位置）
 * @returns {string}
 */
function stateDirPath() {
  const home = Deno.env.get('USERPROFILE') || Deno.env.get('HOME') || '.';
  if (Deno.build.os === 'windows') {
    return join(Deno.env.get('LOCALAPPDATA') || join(home, 'AppData', 'Local'), 'BetterBrowse');
  }
  return join(Deno.env.get('XDG_STATE_HOME') || join(home, '.local', 'state'), 'better-browse');
}

/**
 * 当前系统的浏览器 Native Messaging 注册目录
 * @param {'chrome' | 'edge'} browser
 * @returns {{ dir: string, mode: 'file' | 'registry' }}
 */
function resolveRegistration(browser) {
  const home = Deno.env.get('USERPROFILE') || Deno.env.get('HOME') || '.';
  const os = Deno.build.os;
  if (os === 'windows') {
    // Windows 经注册表指向清单文件；清单与启动器由本脚本落盘
    return { dir: stateDirPath(), mode: 'registry' };
  }
  if (os === 'darwin') {
    const base = join(home, 'Library', 'Application Support');
    const dir = browser === 'edge'
      ? join(base, 'Microsoft Edge', 'NativeMessagingHosts')
      : join(base, 'Google', 'Chrome', 'NativeMessagingHosts');
    return { dir, mode: 'file' };
  }
  // Linux
  const base = join(home, '.config');
  const dir = browser === 'edge'
    ? join(base, 'microsoft-edge', 'NativeMessagingHosts')
    : join(base, 'google-chrome', 'NativeMessagingHosts');
  return { dir, mode: 'file' };
}

async function main() {
  const args = parseArgs(Deno.args);
  const extensionId = String(args['ext-id'] || Deno.args[0] || '').trim().toLowerCase();
  const browser = args.browser === 'edge' ? 'edge' : 'chrome';

  if (!isValidExtensionId(extensionId)) {
    console.error('错误：缺少或非法的扩展 ID。');
    console.error('用法：deno task ai-host-install --ext-id=<扩展ID> [--browser=chrome|edge]');
    console.error('扩展 ID 请在插件选项页「AI 桥接」Tab 中复制（32 位小写字母）。');
    Deno.exit(1);
  }

  const hostDir = import.meta.dirname;
  if (!hostDir) {
    console.error('错误：无法定位宿主脚本目录。');
    Deno.exit(1);
  }

  const hostJsPath = join(hostDir, 'bb_native_host.js');
  try {
    await Deno.stat(hostJsPath);
  } catch {
    console.error(`错误：未找到宿主脚本 ${hostJsPath}，请在仓库内执行安装。`);
    Deno.exit(1);
  }

  // 生成的启动器：把 deno 与宿主脚本的绝对路径烘焙进去，不依赖任何 PATH 解析
  const denoExe = Deno.execPath();
  const stateDir = stateDirPath();
  await Deno.mkdir(stateDir, { recursive: true });

  let launcherPath;
  if (Deno.build.os === 'windows') {
    launcherPath = join(stateDir, 'run-host.cmd');
    const launcher = [
      '@echo off',
      'rem Generated by BetterBrowse ai-host-install. KEEP PURE ASCII.',
      `set "BB_DENO=${denoExe}"`,
      `set "BB_HOST=${hostJsPath}"`,
      'if not exist "%BB_DENO%" set "BB_DENO=deno"',
      '"%BB_DENO%" run -A --quiet "%BB_HOST%" %*',
      ''
    ].join('\r\n');
    await Deno.writeTextFile(launcherPath, launcher);
  } else {
    launcherPath = join(stateDir, 'run-host.sh');
    const launcher = [
      '#!/bin/sh',
      '# Generated by BetterBrowse ai-host-install.',
      `BB_DENO="${denoExe}"`,
      `BB_HOST="${hostJsPath}"`,
      '[ -x "$BB_DENO" ] || BB_DENO="$(command -v deno)"',
      'exec "$BB_DENO" run -A --quiet "$BB_HOST" "$@"',
      ''
    ].join('\n');
    await Deno.writeTextFile(launcherPath, launcher);
    try {
      await Deno.chmod(launcherPath, 0o755);
    } catch {
      // 部分文件系统不支持 chmod，忽略
    }
  }

  const manifest = {
    name: HOST_NAME,
    description: HOST_DESCRIPTION,
    path: launcherPath,
    type: 'stdio',
    allowed_origins: [`chrome-extension://${extensionId}/`]
  };

  const { dir, mode } = resolveRegistration(browser);
  await Deno.mkdir(dir, { recursive: true });
  const manifestPath = join(dir, `${HOST_NAME}.json`);
  await Deno.writeTextFile(manifestPath, JSON.stringify(manifest, null, 2));

  if (mode === 'registry') {
    const keyPath = browser === 'edge'
      ? 'HKCU\\Software\\Microsoft\\Edge\\NativeMessagingHosts\\com.betterbrowse.bridge'
      : 'HKCU\\Software\\Google\\Chrome\\NativeMessagingHosts\\com.betterbrowse.bridge';
    const command = new Deno.Command('reg', {
      args: ['add', keyPath, '/ve', '/t', 'REG_SZ', '/d', manifestPath, '/f'],
      stdout: 'piped',
      stderr: 'piped'
    });
    const output = await command.output();
    if (!output.success) {
      console.error('错误：写入注册表失败：');
      console.error(new TextDecoder().decode(output.stderr));
      Deno.exit(1);
    }
  }

  console.log('✅ AI 桥接宿主安装完成');
  console.log(`   浏览器：${browser}`);
  console.log(`   扩展 ID：${extensionId}`);
  console.log(`   Deno 路径（已烘焙进启动器）：${denoExe}`);
  console.log(`   启动器：${launcherPath}`);
  console.log(`   注册位置：${manifestPath}${mode === 'registry' ? '（经 HKCU 注册表指向）' : ''}`);
  console.log('');
  console.log('后续步骤：');
  console.log('  1. 在 chrome://extensions 重载 BetterBrowse 扩展；');
  console.log('  2. 在选项页「AI 桥接」Tab 开启总开关；');
  console.log('  3. 运行 skills/better-browse/scripts/bb-bridge-client.js status 验证连通。');
}

await main();
