/**
 * @file install.js
 * @description AI 桥接本机宿主安装器（注册 Native Messaging 宿主清单 + 平台入口）
 *
 * 用法：
 *   deno task ai-host-install --ext-id=<扩展ID>
 *   可选 --browser=chrome|edge（默认 chrome）
 *
 * 扩展 ID 从选项页「AI 桥接」Tab 复制（32 位 a-p 字母）。
 * 幂等：重复执行直接覆盖旧注册。Chrome 与 Edge 各自独立注册，互不覆盖。
 *
 * ⚠️ Windows 实现要点：启动器由本脚本生成到用户状态目录，并把 deno 绝对路径烘焙进去。
 * Chrome 是长驻进程，其子进程环境可能滞后于当前 shell 的 PATH（装完 deno 后未重启
 * Chrome 时尤为典型），依赖 `deno` 命令解析会导致宿主秒退（"Native host has exited"）。
 * 启动器必须保持纯 ASCII：cmd.exe 以 ANSI 代码页解析批处理，UTF-8 中文注释或中文路径
 * 都会破坏解析，非 ASCII 路径经 toBatchSafePath 改写为环境变量前缀或 8.3 短路径。
 * @encoding UTF-8
 */

import { join } from 'jsr:@std/path@^1.0.8';
import { HOST_NAME, parseArgs, parseBrowser, resolveRegistration, stateDirPath } from './host-paths.js';

const HOST_DESCRIPTION = 'BetterBrowse AI 桥接本机宿主（由 Chrome 按需拉起，非常驻服务）';
const ASCII_PATTERN = /^[\x20-\x7e]*$/;

/**
 * 校验扩展 ID（Chrome 无序 ID：32 位 a-p 小写字母）
 * @param {string} id
 */
function isValidExtensionId(id) {
  return /^[a-p]{32}$/.test(String(id || '').trim());
}

/**
 * 把路径改写为可安全写进 .cmd 的纯 ASCII 形式：
 * 优先用 %LOCALAPPDATA% / %APPDATA% / %USERPROFILE% 前缀替换（运行时展开为 Unicode 原值），
 * 仍含非 ASCII 时退回 8.3 短路径。
 * @param {string} path
 * @returns {Promise<string>}
 */
async function toBatchSafePath(path) {
  if (ASCII_PATTERN.test(path)) return path;
  for (const name of ['LOCALAPPDATA', 'APPDATA', 'USERPROFILE']) {
    const value = Deno.env.get(name);
    if (value && path.toLowerCase().startsWith(value.toLowerCase())) {
      const rewritten = `%${name}%${path.slice(value.length)}`;
      if (ASCII_PATTERN.test(rewritten)) return rewritten;
    }
  }
  try {
    const output = await new Deno.Command('cmd', {
      args: ['/d', '/c', `for %I in ("${path}") do @echo %~sI`],
      stdout: 'piped',
      stderr: 'null'
    }).output();
    const shortPath = new TextDecoder().decode(output.stdout).trim();
    if (output.success && shortPath && ASCII_PATTERN.test(shortPath)) return shortPath;
  } catch {
    // 卷禁用了 8.3 短名称时无法转换，保留原值并提示
  }
  console.warn(`警告：路径含非 ASCII 字符且无法转换为短路径，宿主可能无法启动：${path}`);
  return path;
}

async function main() {
  const args = parseArgs(Deno.args);
  const extensionId = String(args['ext-id'] || Deno.args[0] || '').trim().toLowerCase();
  const browser = parseBrowser(args);

  if (!isValidExtensionId(extensionId)) {
    console.error('错误：缺少或非法的扩展 ID。');
    console.error('用法：deno task ai-host-install --ext-id=<扩展ID> [--browser=chrome|edge]');
    console.error('扩展 ID 请在插件选项页「AI 桥接」Tab 中复制（32 位小写字母）。');
    Deno.exit(1);
  }

  const hostDir = import.meta.dirname;
  if (!hostDir) {
    console.error('错误：无法定位宿主脚本目录。');
    Deno.exit(1);
  }

  const hostJsPath = join(hostDir, 'bb_native_host.js');
  try {
    await Deno.stat(hostJsPath);
  } catch {
    console.error(`错误：未找到宿主脚本 ${hostJsPath}，请在仓库内执行安装。`);
    Deno.exit(1);
  }

  // 生成的启动器：把 deno 与宿主脚本的绝对路径烘焙进去，不依赖任何 PATH 解析
  const denoExe = Deno.execPath();
  const stateDir = stateDirPath();
  await Deno.mkdir(stateDir, { recursive: true });

  let launcherPath;
  if (Deno.build.os === 'windows') {
    launcherPath = join(stateDir, 'run-host.cmd');
    const launcher = [
      '@echo off',
      'rem Generated by BetterBrowse ai-host-install. KEEP PURE ASCII.',
      `set "BB_DENO=${await toBatchSafePath(denoExe)}"`,
      `set "BB_HOST=${await toBatchSafePath(hostJsPath)}"`,
      'if not exist "%BB_DENO%" set "BB_DENO=deno"',
      '"%BB_DENO%" run -A --quiet "%BB_HOST%" %*',
      ''
    ].join('\r\n');
    await Deno.writeTextFile(launcherPath, launcher);
  } else {
    launcherPath = join(stateDir, 'run-host.sh');
    const launcher = [
      '#!/bin/sh',
      '# Generated by BetterBrowse ai-host-install.',
      `BB_DENO="${denoExe}"`,
      `BB_HOST="${hostJsPath}"`,
      '[ -x "$BB_DENO" ] || BB_DENO="$(command -v deno)"',
      'exec "$BB_DENO" run -A --quiet "$BB_HOST" "$@"',
      ''
    ].join('\n');
    await Deno.writeTextFile(launcherPath, launcher);
    try {
      await Deno.chmod(launcherPath, 0o755);
    } catch {
      // 部分文件系统不支持 chmod，忽略
    }
  }

  const manifest = {
    name: HOST_NAME,
    description: HOST_DESCRIPTION,
    path: launcherPath,
    type: 'stdio',
    allowed_origins: [`chrome-extension://${extensionId}/`]
  };

  const { dir, mode, manifestPath, registryKey } = resolveRegistration(browser);
  await Deno.mkdir(dir, { recursive: true });
  await Deno.writeTextFile(manifestPath, JSON.stringify(manifest, null, 2));

  if (mode === 'registry') {
    const output = await new Deno.Command('reg', {
      args: ['add', registryKey, '/ve', '/t', 'REG_SZ', '/d', manifestPath, '/f'],
      stdout: 'piped',
      stderr: 'piped'
    }).output();
    if (!output.success) {
      console.error('错误：写入注册表失败：');
      console.error(new TextDecoder().decode(output.stderr));
      Deno.exit(1);
    }
  }

  console.log('✅ AI 桥接宿主安装完成');
  console.log(`   浏览器：${browser}`);
  console.log(`   扩展 ID：${extensionId}`);
  console.log(`   Deno 路径（已烘焙进启动器）：${denoExe}`);
  console.log(`   启动器：${launcherPath}`);
  console.log(`   注册位置：${manifestPath}${mode === 'registry' ? '（经 HKCU 注册表指向）' : ''}`);
  console.log('');
  console.log('后续步骤：');
  console.log('  1. 在 chrome://extensions 重载 BetterBrowse 扩展；');
  console.log('  2. 在选项页「AI 桥接」Tab 开启总开关；');
  console.log('  3. 使用 Python 3.9+ 运行 skills/BetterBrowse/scripts/betterbrowse_client.py doctor 验证连通。');
}

await main();
